<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sparql_toucan"
 *
 * Auto generated by Extension Builder 2020-10-27
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Sparql Toucan',
    'description' => 'An Extension that fills parts of the website with the content of a semantic data source. Uses a triplestore as remote database',
    'category' => 'plugin',
    'author' => 'JPKanter',
    'author_email' => 'bdd_dev@ub.uni-leipzig.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.5.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
